export type Exchange='upbit'|'bithumb'|'coinone';
export type Coin={symbol:string;name:string;price:number;change:number;volume:number;timestamp:number};
export type Candle={time:number;close:number;volume:number};
export const exchanges={upbit:'업비트',bithumb:'빗썸',coinone:'코인원'};
export function exchangeOf(s:unknown):Exchange{if(s==='upbit'||s==='bithumb'||s==='coinone')return s;throw new Error('거래소를 선택해 주세요.');}
export function symbolOf(s:unknown){if(typeof s==='string'&&/^[A-Z0-9]{1,20}$/.test(s))return s;throw new Error('올바른 종목이 아닙니다.');}
const names:Record<string,string>={BTC:'비트코인',ETH:'이더리움',XRP:'리플',SOL:'솔라나',DOGE:'도지코인',ADA:'에이다',LINK:'체인링크',AVAX:'아발란체',SUI:'수이',TRX:'트론',DOT:'폴카닷'};
export async function json(url:string){const r=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`거래소 응답 지연 (${r.status}). 잠시 후 다시 시도해 주세요.`);return r.json() as Promise<any>;}
const base=(e:Exchange)=>e==='upbit'?'https://api.upbit.com':'https://api.bithumb.com';
export async function market(e:Exchange):Promise<Coin[]>{
 let result:Coin[]=[];
 if(e==='coinone'){const d=await json('https://api.coinone.co.kr/public/v2/ticker_new/KRW');if(d.result!=='success'||!Array.isArray(d.tickers))throw new Error('코인원 시세를 불러오지 못했습니다.');result=d.tickers.map((c:any)=>({symbol:c.target_currency,name:names[c.target_currency]||c.target_currency,price:+c.last,change:(+c.last/+c.first-1)*100,volume:+c.quote_volume,timestamp:+d.timestamp}));}
 else{const all=await json(base(e)+'/v1/market/all');if(!Array.isArray(all))throw new Error('종목 목록을 불러오지 못했습니다.');const list=all.filter((c:any)=>c.market.startsWith('KRW-'));for(let i=0;i<list.length;i+=80){const group=list.slice(i,i+80);const ticks=await json(base(e)+'/v1/ticker?markets='+group.map((c:any)=>c.market).join(','));if(!Array.isArray(ticks))throw new Error('시세 형식이 올바르지 않습니다.');result.push(...ticks.map((c:any)=>({symbol:c.market.slice(4),name:group.find((x:any)=>x.market===c.market)?.korean_name||c.market.slice(4),price:+c.trade_price,change:+c.signed_change_rate*100,volume:+c.acc_trade_price_24h,timestamp:+c.timestamp})));}}
 return result.filter(c=>Number.isFinite(c.price)&&c.price>0).sort((a,b)=>b.volume-a.volume);
}
export async function candles(e:Exchange,symbol:string):Promise<Candle[]>{let out:Candle[];if(e==='coinone'){const d=await json(`https://api.coinone.co.kr/public/v2/chart/KRW/${symbol}?interval=1h&size=200`);if(!Array.isArray(d.chart))throw new Error('과거 이력을 불러오지 못했습니다.');out=d.chart.map((c:any)=>({time:+c.timestamp,close:+c.close,volume:+c.target_volume}));}else{const d=await json(`${base(e)}/v1/candles/minutes/60?market=KRW-${symbol}&count=200`);if(!Array.isArray(d))throw new Error('과거 이력을 불러오지 못했습니다.');out=d.map((c:any)=>({time:Date.parse(c.candle_date_time_utc+'Z'),close:+c.trade_price,volume:+c.candle_acc_trade_volume}));}return out.filter(c=>c.time+3600000<=Date.now()&&Number.isFinite(c.close)&&c.close>0).sort((a,b)=>a.time-b.time);}
export async function book(e:Exchange,symbol:string){let bids:any[],asks:any[];let timestamp:number;if(e==='coinone'){const d=await json(`https://api.coinone.co.kr/public/v2/orderbook/KRW/${symbol}?size=15`);bids=d.bids;asks=d.asks;timestamp=+d.timestamp;}else{const d=await json(`${base(e)}/v1/orderbook?markets=KRW-${symbol}`);const row=d[0];if(!row)throw new Error('호가를 확인할 수 없습니다.');bids=row.orderbook_units.map((x:any)=>({price:x.bid_price,qty:x.bid_size}));asks=row.orderbook_units.map((x:any)=>({price:x.ask_price,qty:x.ask_size}));timestamp=+row.timestamp;}if(!Array.isArray(bids)||!Array.isArray(asks)||!Number.isFinite(timestamp)||Date.now()-timestamp>60000||timestamp>Date.now()+10000)throw new Error('호가가 오래되었거나 유효하지 않아 모의 주문을 중단했습니다.');const normalize=(a:any[])=>a.map(x=>({price:+x.price,qty:+x.qty})).filter(x=>Number.isFinite(x.price)&&Number.isFinite(x.qty)&&x.price>0&&x.qty>0);return{bids:normalize(bids).sort((a,b)=>b.price-a.price),asks:normalize(asks).sort((a,b)=>a.price-b.price),timestamp};}
export function analyze(cs:Candle[]){if(cs.length<60)throw new Error('분석에 필요한 완료된 1시간봉이 60개 미만입니다.');const p=cs.map(x=>x.close);const avg=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;const last=p.at(-1)!;const ma20=avg(p.slice(-20)),ma60=avg(p.slice(-60));const changes=p.slice(-15).slice(1).map((x,i)=>x-p[p.length-15+i]);const gains=avg(changes.map(x=>Math.max(x,0))),losses=avg(changes.map(x=>Math.max(-x,0)));const rsi=losses===0?(gains===0?50:100):100-100/(1+gains/losses);const returns=p.slice(1).map((x,i)=>(x/p[i]-1)*100);const vol=Math.sqrt(avg(returns.slice(-24).map(x=>(x-avg(returns.slice(-24)))**2)));const volumeRatio=cs.at(-1)!.volume/Math.max(avg(cs.slice(-21,-1).map(x=>x.volume)),1e-12);const score=Math.max(0,Math.min(100,50+(last>ma20?15:-15)+(ma20>ma60?15:-15)+(rsi>=45&&rsi<70?10:-10)+(volumeRatio>1.2?10:0)));const signal=score>=80&&rsi<70?'매수 검토':score<=30||rsi>80?'매도 검토':'관망';return{score,signal,rsi,ma20,ma60,volumeRatio,volatility:vol,candles:cs,last,asOf:cs.at(-1)!.time,reason:`완료된 1시간봉 ${cs.length}개 기준. 현재 종가는 20시간 평균 ${last>ma20?'위':'아래'}, 20시간 평균은 60시간 평균 ${ma20>ma60?'위':'아래'}입니다. RSI ${rsi.toFixed(1)}, 최근 거래량 ${volumeRatio.toFixed(2)}배.`,method:'추세·RSI·거래량 규칙 v1. 점수는 상승 확률이 아니며 수익성 검증 전입니다.'};}
